### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by YouROK** [deranjer/goTorrent#19]
Check this line, there is a limit download for upload size
https://github.com/deranjer/goTorrent/blob/49094293904bcca5f636ea58646465bf5fda5d0c/settings/settings.go#L105

**Comment by deranjer** [comment]
Hey, thanks for catching that, I've corrected it and it will be fixed in the next release.  Currently rewriting the entire core of the server and that is taking much longer than anticipated, so no ETA on that...
