### ISSUE TITLE
Add .torrent files from monitored folder

### ISSUE THREAD

**Issue by deranjer** [deranjer/goTorrent#4]
Will be implemented as a cron job to check a specified folder every 5 minutes to see if any .torrent files are in the folder, if so attempt to add them, then copy to our .torrent backup folder and delete the .torrent file

**Comment by iamacarpet** [comment]
Hello @deranjer,

Sorry it’s been a while to show up, been a little busy.

I did a little research after you rightly pointed out that inotify is Linux only, and there’s a Go project called fsnotify that supports cross-platform (Windows/Mac/Linux/Solaris/BSD) file system notifications.

If that’s a satisfactory list of supported operating systems, notifications might be a bit more lightweight and responsive than a scheduled job / cron.

https://github.com/fsnotify/fsnotify

Regards,
iamacarpet

**Comment by deranjer** [comment]
I am currently testing the https://godoc.org/github.com/robfig/cron package which I am already using to do an hourly scrape of RSS feeds.  It checks the folder every 5 minutes and adds new torrents.  I just completed the coding, but have a lot of testing to do on the feature yet.  Would that be an acceptable?

If not, the fsnotify package does look easy to implement so I could go that direction as well.
